name: Step 2, Add a Dockerfile

# This step triggers after we push changes to `Dockerfile` on branch `cd`
# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run every time we push changes to `Dockerfile` on branch `cd`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - cd
    paths:
      - Dockerfile

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_push_dockerfile:
    name: On push Dockerfile

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # Check the learner added intended contents to the file
      - name: Verify Dockerfile contents
        run: ./.github/script/check-file.sh
        env:
          FILE: "Dockerfile"
          SEARCH: "FROM nginx:1.17"

      # Update README to close <details id=2> and open <details id=3>
      # and set STEP to '3'
      - name: Update to step 3
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: cd
